FROM mdmoore25404/speciesnet-base:latest

WORKDIR /app

# Install RunPod dependency
RUN pip install --no-cache-dir runpod

COPY detectord.py common.py ./
COPY run-detector.sh ./run.sh
RUN chmod +x run.sh

RUN mkdir -p /tmp/shared_temp && chmod 1777 /tmp/shared_temp

CMD ["python", "detectord.py"]