#!/usr/bin/env bash
# Script to generate requirements.txt while excluding problematic directories

# Define directories to exclude
EXCLUDE_DIRS="__pycache__,models,weights,checkpoints,venv,tcam,data,PytorchWildlife,notebooks,examples,.git,.vscode,ultralytics,speciesnetd-env"

# Run pipreqs with exclusions and encoding specification
pipreqs --encoding=utf8 --ignore=$EXCLUDE_DIRS --force --mode compat ./

# Check if pipreqs was successful
if [ $? -eq 0 ]; then
    echo "Successfully generated requirements.txt"
    
    
    
    
    echo "Contents of requirements.txt:"
    cat requirements.txt
else
    echo "Error running pipreqs. Generating basic requirements manually..."
    
    # Create a basic requirements.txt file with common dependencies using ~= operator
    cat > requirements.txt << EOF
# Automatically generated by pipreqs.sh
numpy~=1.20.0
opencv-python~=4.5.0
Pillow~=8.0.0
requests~=2.25.0
torch~=1.10.0
ultralytics~=8.0.0  # For YOLO models
PytorchWildlife~=0.1.0  # For MegaDetectorV6
EOF
    
    echo "Created basic requirements.txt with ~= operators"
    echo "Contents of requirements.txt:"
    cat requirements.txt
fi

echo ""
echo "You may need to manually adjust version requirements."
echo "The ~= operator specifies compatibility with a version (same major.minor version, ≥ specified patch version)"