name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/detectord
            ghcr.io/${{ github.repository_owner }}/classifierd
            
      # Build and push detector image
      - name: Build and push detector image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.detector
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/detectord:latest
            ghcr.io/${{ github.repository_owner }}/detectord:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      # Build and push classifier image
      - name: Build and push classifier image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.classifier
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/classifierd:latest
            ghcr.io/${{ github.repository_owner }}/classifierd:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max